spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require&connectionTimeout=30000&socketTimeout=30000
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 30000
      leak-detection-threshold: 5000
      initialization-fail-timeout: 0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

server:
  shutdown: graceful